# Final Project
## Machine Learning for Neuroscience
### Gaia Negev and Tzlil Tabib

In [ ]:
# load data from json
import json
with open('emoset_challenge_1000_augmented.json', 'r') as f:
    data = json.load(f)

In [ ]:
# data to pd.DataFrame
import pandas as pd
df = pd.DataFrame(data)
df_annotations = pd.DataFrame(df['annotations'].tolist())
df = pd.concat([df.drop('annotations', axis=1), df_annotations], axis=1)
df.head()

# remove image_name column
df = df.drop('image_name', axis=1)
# make image_id the index
df = df.set_index('image_id')
df.head()

,description,embedding,viewer_feelings,description_embedding,viewer_feelings_embedding,emotion,brightness,colorfulness,facial_expression,object,human_action,scene
image_id,,,,,,,,,,,,
anger_05461,"A group of young women stands outdoors, raisin...","[-0.003466871799901128, 0.008943479508161545, ...",A viewer might feel a strong sense of empowerm...,"[0.015244223177433014, 0.02191872149705887, 0....","[0.04869891703128815, 0.011180873960256577, -0...",anger,0.7,0.3,angry,NaN,NaN,NaN
anger_04009,A basketball coach is animatedly addressing a ...,"[-0.02497812733054161, -3.173016921209637e-06,...",A viewer might feel a sense of intensity and u...,"[-0.0480334609746933, 0.0048103006556630135, -...","[0.026645997539162636, 0.03669874370098114, -0...",anger,0.4,0.6,angry,NaN,NaN,NaN
excitement_14481,The image depicts a lively street scene during...,"[0.0060758707113564014, -0.05795256420969963, ...",A viewer might feel a sense of joy and celebra...,"[0.08013048022985458, 0.003585593309253454, 0....","[0.08260990679264069, -0.024715717881917953, -...",excitement,0.5,0.5,NaN,"[Building, Shorts]",NaN,NaN
disgust_09637,"A middle-aged man with dark, weathered skin is...","[0.015266705304384232, -0.03632277995347977, -...",A viewer might feel a sense of solemnity and c...,"[0.024899128824472427, 0.007712359540164471, -...","[0.03756456822156906, 0.016621604561805725, -0...",disgust,0.3,0.3,NaN,NaN,smoking,NaN
amusement_13130,The image features a brightly lit amusement ri...,"[-0.027908993884921074, 0.010876640677452087, ...",A viewer might feel a sense of exhilaration an...,"[0.014399278908967972, 0.005827619694173336, -...","[0.023505138233304024, 0.00531125720590353, -0...",amusement,0.3,0.9,NaN,NaN,NaN,amusement_park

# EDA

In [ ]:
df.describe()

       brightness  colorfulness
count  999.000000    976.000000
mean     0.483884      0.493545
std      0.151183      0.195302
min      0.000000      0.000000
25%      0.400000      0.400000
50%      0.500000      0.500000
75%      0.600000      0.600000
max      0.900000      1.000000

In [ ]:
# null analysis
df.isnull().sum()

description                    0
embedding                      0
viewer_feelings                0
description_embedding          0
viewer_feelings_embedding      0
emotion                        0
brightness                     1
colorfulness                  24
facial_expression            888
object                       487
human_action                 886
scene                        788
dtype: int64

In [ ]:
#  facial expression distribution
import matplotlib.pyplot as plt
df['facial_expression'].value_counts().plot(kind='bar')
plt.title('Facial Expression Distribution')
plt.xlabel('Facial Expression')
plt.ylabel('Count')
plt.show()